spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true

springdoc:
  enable-hateoas: true
  api-docs:
    enabled: true
    path: classpath:api_doc
    resolve-schema-properties: true
  show-oauth2-endpoints: true
  swagger-ui:
    url: /documentation
    version: 31
